### PR TITLE
Bug fix in `find-by` + Add column qualifier type option & ts per cell option 

### PR DESCRIPTION
**Pull request by viebel**

### CODE REVIEW

**Comment by viebel** [comment]
@tolitius Could someone review this PR?

**Comment by tolitius** [comment]
looks like this branch has conflicts: i.e. can't be merged

I think you are doing something strange with merging or rebasing, since every change comes in a form of maaaaany commits 👆 , where in reality your change is good and not all that large.

as to reviewing it, test it in REPL with a local HBase
of course tests are welcome as well :)

**Comment by viebel** [comment]
Commit mess has been fixed.
Tested locally.
Please merge

**Comment by tolitius** [comment]
great, thanks @viebel!

**Pull request merged**
