### PR TITLE
Support timestamp in store and time-range in find-by

### PR DESCRIPTION
**Pull request by viebel**
- Support custom timestamp in `store` and `store-batch`
- Support time-range in `find-by`

### CODE REVIEW

**Comment by viebel** [comment]
Could you review this PR?

**Review by tolitius — APPROVED** [review]
code looks good
one thing would be really helpful, as there are a lot of changes coming in, is to start adding tests for these functions

let me know whether you have time to do it now
or we can merge it now (if you tried it and it worked) and you may be have time to do it later on

hbase, by itself, is a complex, mutable beast with quite extensive API corner cases, so tests would allow us some piece of mind once things are changed

**Comment by viebel** [comment]
I'd prefer to merge and deploy it now and add tests later.
I have tested it for real and it works fine.

**Comment by tolitius** [comment]
cool, let's do add tests later

**Pull request merged**
