### PR TITLE
Fix delete-by and add keys-only? option to scan

### PR DESCRIPTION
**Pull request by viebel**

### CODE REVIEW

**Comment by viebel** [comment]
- Add support for `:keys-only` in `scan` and `lazy-scan`
- Improve efficiency of `delete-by` by passing to lazy-scan `:keys-only true`

**Comment by tolitius** [comment]
great, thanks for the pr!

**Comment by tolitius** [comment]
should be in `0.2.8`

**Comment by viebel** [comment]
Thank you!

**Pull request merged**
